backend/simprosis/olahDataJurnalKuliah/urls.py
from django.urls import path, re_path, include
from django.conf.urls import url
from . views import (
    jurnalKuliahListView,
    jurnalKuliahCreateView,
    jurnalPerkuliahanCreateView,
    jurnalPerkuliahanUpdateView,
    jurnalKuliahDeleteView,
    jurnalKuliahDetailView,
    importPesertaKuliah
)

app_name='olahDataJurnalKuliah'
urlpatterns = [
    re_path(r'^$',jurnalKuliahListView.as_view(),name='jurnalKuliahList'),
    re_path(r'^createjurnal/$',jurnalKuliahCreateView.as_view(),name='jurnal-add'),
    re_path(r'^updatejurnal/(?P<pk>[0-9]+)$',jurnalPerkuliahanUpdateView.as_view(),name='jurnal-update'),
    re_path(r'^deletejurnal/(?P<pk>[0-9]+)$',jurnalKuliahDeleteView.as_view(),name='jurnal-delete'),
    re_path(r'^detailjurnal/(?P<pk>[0-9]+)$',jurnalKuliahDetailView.as_view(),name='detailjurnal'),
    re_path(r'^importPesertaKuliah/(?P<idJurnal>[0-9]+)$',importPesertaKuliah, name='importPesertaKuliah'),
]

backend/simprosis/rps/urls.py
#urls RPS
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name='rps'
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^submenurps/$',views.submenurps),
    re_path(r'^profile/$',views.profile,name='profile'),
    path('fakultas/',views.fakultasListView.as_view(),name='fakultasList'),
    re_path(r'^updatefakultas/(?P<pk>[0-9]+)$',views.fakProdiUpdateView.as_view(),name='fakultas-update'),
    re_path(r'^deletefakultas/(?P<pk>[0-9]+)$',views.fakultasDeleteView.as_view(),name='fakultas-delete'),
    re_path(r'^createfakultas$',views.fakProdiCreateView.as_view(),name='fakultas-add')
]

backend/simprosis/simprosis/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^rps/',include('rps.urls',namespace='rps')), #menghubungkan url rps dengan url project simprosis
    re_path(r'^biodataDosen/',include('biodataDosen.urls',namespace='biodataDosen')),
    re_path(r'^biodataMahasiswa/',include('biodataMahasiswa.urls',namespace='biodataMahasiswa')),
    re_path(r'^inputKRS/',include('inputKRS.urls',namespace='inputKRS')),
    re_path(r'^olahDataDosen/',include('olahDataDosen.urls', namespace='olahDataDosen')),
    re_path(r'^olahDataJurnalKuliah/',include('olahDataJurnalKuliah.urls',namespace='olahDataJurnalKuliah')),
    re_path(r'^olahDataMahasiswa/',include('olahDataMahasiswa.urls',namespace='olahDataMahasiswa')),
    re_path(r'^olahDataMatakuliah/',include('olahDataMatakuliah.urls',namespace='olahDataMatakuliah')),
    re_path(r'^olahDataNilai/',include('olahDataNilai.urls',namespace='olahDataNilai')),
    re_path(r'^olahDataRPS/',include('olahDataRPS.urls',namespace='olahDataRPS')),
    re_path(r'^presensiKuliah/',include('presensiKuliah.urls',namespace='presensiKuliah')),
    re_path(r'^rekapHasilKuliah/',include('rekapHasilKuliah.urls',namespace='rekapHasilKuliah')),
    re_path(r'^rekapKRS/',include('rekapKRS.urls',namespace='rekapKRS')),
    re_path(r'^rekapPresensi/',include('rekapPresensi.urls', namespace='rekapPresensi')),
    re_path(r'^rekapRPS/',include('rekapRPS.urls',namespace='rekapRPS')),
    re_path(r'^subPokokBahasan/',include('subPokokBahasan.urls',namespace='subPokokBahasan')),
    re_path(r'^tes/$',views.tes),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('',views.index, name='index')
]

backend/simprosis/templates/snipets/logoutModal.html
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Yakin Logout ? </h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
        </button>
    </div>
    <div class="modal-body">Pilih "Logout" di bawah ini, jika anda yakin untuk mengakhiri session anda.</div>
    <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="login.html">Logout</a>
    </div>
    </div>
</div>
</div>

backend/simprosis/templates/snipets/scripts.html
{% load static %}
<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'vendor/jquery/jquery.js' %}"></script>
<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<!-- Page level plugins -->
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

<!-- date picker -->
<!-- <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script> -->

<!-- <script src="{% static 'vendor/bootstrap/js/bootstrap-datetimepicker.min.js' %}"></script> -->
<!-- <script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script> -->

backend/simprosis/templates/snipets/sidebar.html
 {% load static %}
 <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
          <div class="sidebar-brand-icon">
            <i><img style="height: 30px;" src="{% static 'img/icon_unp_trans.png' %}" alt=""></i>
          </div>
          <div class="sidebar-brand-text mx-3">SISFORM <sup>SMART</sup></div>
        </a>
  
        <!-- Divider -->
        <hr class="sidebar-divider my-0">
  
        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
        </li>
  
        <!-- Divider -->
        <hr class="sidebar-divider">
  
        <!-- Heading -->
        <div class="sidebar-heading">
          APLIKASI
        </div>
  
        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Operasional" aria-expanded="true" aria-controls="Operasional">
            <i class="fas fa-fw fa-cogs"></i>
            <span>Operasional</span>
          </a>
          <div id="Operasional" class="collapse" aria-labelledby="headingTwos" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Menu Operasional</h6>
              <a class="collapse-item" href="{% url 'olahDataDosen:index' %}">Olah Data Dosen</a>
              <a class="collapse-item" href="{% url 'olahDataMahasiswa:index' %}">Olah Data Mahasiswa</a>
              <a class="collapse-item" href="{% url 'olahDataMatakuliah:index' %}">Olah Data Matakuliah</a>
              <a class="collapse-item" href="{% url 'olahDataJurnalKuliah:jurnalKuliahList' %}">Olah Data Jurnal Kuliah</a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Laporan" aria-expanded="true" aria-controls="Laporan">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Laporan</span>
          </a>
          <div id="Laporan" class="collapse" aria-labelledby="headingTwos" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Menu Laporan</h6>
              <a class="collapse-item" href="{% url 'rekapRPS:index' %}">Rekap RPS</a>
              <a class="collapse-item" href="{% url 'rekapKRS:index' %}">Rekap KRS</a>
              <a class="collapse-item" href="{% url 'rekapPresensi:index' %}">Rekap Presensi</a>
              <a class="collapse-item" href="{% url 'rekapHasilKuliah:index' %}">Rekap Hasil Kuliah</a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Dosen" aria-expanded="true" aria-controls="Dosen">
            <i class="fas fa-fw fa-user"></i>
            <span>Dosen</span>
          </a>
          <div id="Dosen" class="collapse" aria-labelledby="headingTwos" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Menu Dosen</h6>
              <a class="collapse-item" href="{% url 'biodataDosen:index' %}">Biodata Dosen</a>
              <a class="collapse-item" href="{% url 'olahDataRPS:index' %}">Olah data RPS</a>
              <a class="collapse-item" href="{% url 'olahDataNilai:index' %}">Olah Data Nilai</a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Presensi" aria-expanded="true" aria-controls="Presensi">
            <i class="fas fa-fw fa-calendar-check"></i>
            <span>Presensi</span>
          </a>
          <div id="Presensi" class="collapse" aria-labelledby="headingTwos" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Menu Presensi</h6>
              <a class="collapse-item" href="{% url 'subPokokBahasan:index' %}">Sub-Pokok Bahasan</a>
              <a class="collapse-item" href="{% url 'presensiKuliah:index' %}">Presensi Kuliah</a>
              <a class="collapse-item" href="{% url 'rekapPresensi:index' %}">Rekap Presensi</a>
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#Mahasiswa" aria-expanded="true" aria-controls="Mahasiswa">
            <i class="fas fa-fw fa-graduation-cap"></i>
            <span>Mahasiswa</span>
          </a>
          <div id="Mahasiswa" class="collapse" aria-labelledby="headingTwos" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Menu Mahasiswa</h6>
              <a class="collapse-item" href="{% url 'biodataMahasiswa:index' %}">Biodata Mahasiswa</a>
              <a class="collapse-item" href="{% url 'inputKRS:index' %}">Input KRS</a>
            </div>
          </div>
        </li>
  
        
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
  
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
  
      </ul>
      <!-- End of Sidebar -->

backend/simprosis/templates/snipets/styles.html
{% load static %}

<!-- Custom fonts for this template-->
<link href="{% static 'vendor/fontawesome-free/css/all.min.css' %} " rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static 'css/sb-admin-2.min.css' %} " rel="stylesheet">

<!-- datepicker -->
<!-- <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap-datetimepicker.min.css' %}"> -->
<!-- <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> -->
<!-- <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet"> -->

backend/simprosis/templates/snipets/topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <div class="d-sm-flex align-items-center ">
      <h5 class="m-0 font-weight-bold">{{appGroup}}</h5>
    </div>
    <ul class="navbar-nav ml-auto">
      <div class="topbar-divider d-none d-sm-block"></div>

      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">Selamat Datang :
            <!-- {{ user.username }} -->
          </span>
          <i class="fas fa-fw fa-user-circle" style="font-size:24px;"></i>
          <!-- <img class="img-profile " src="{% static 'img/icon_unp_trans.png' %} "> -->
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url 'rps:profile' %}">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <a class="dropdown-item" href="#">
            <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
            Activity Log
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>