backend/simprosis/olahDataMahasiswa/urls.py
from django.urls import path, re_path, include
from django.conf.urls import url
from .views import (
    mahasiswaCreateView,
    mahasiswaUpdateView,
    mahasiswaListView,
    mahasiswaDeleteView,
    importDataMhs
)

app_name='olahDataMahasiswa'
urlpatterns = [
    re_path(r'^$',mahasiswaListView.as_view(),name='index'),
    re_path(r'^import$',importDataMhs, name='import'),
    re_path(r'^create/$',mahasiswaCreateView.as_view(),name='create'),
    re_path(r'^update/(?P<pk>[0-9]+)$',mahasiswaUpdateView.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>[0-9]+)$',mahasiswaDeleteView.as_view(),name='delete')
]

backend/simprosis/rps/urls.py
#urls RPS
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name='rps'
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^submenurps/$',views.submenurps),
    re_path(r'^profile/$',views.profile,name='profile'),
    path('fakultas/',views.fakultasListView.as_view(),name='fakultasList'),
    re_path(r'^updatefakultas/(?P<pk>[0-9]+)$',views.fakProdiUpdateView.as_view(),name='fakultas-update'),
    re_path(r'^deletefakultas/(?P<pk>[0-9]+)$',views.fakultasDeleteView.as_view(),name='fakultas-delete'),
    re_path(r'^createfakultas$',views.fakProdiCreateView.as_view(),name='fakultas-add')
]

backend/simprosis/simprosis/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^rps/',include('rps.urls',namespace='rps')), #menghubungkan url rps dengan url project simprosis
    re_path(r'^biodataDosen/',include('biodataDosen.urls',namespace='biodataDosen')),
    re_path(r'^biodataMahasiswa/',include('biodataMahasiswa.urls',namespace='biodataMahasiswa')),
    re_path(r'^inputKRS/',include('inputKRS.urls',namespace='inputKRS')),
    re_path(r'^olahDataDosen/',include('olahDataDosen.urls', namespace='olahDataDosen')),
    re_path(r'^olahDataJurnalKuliah/',include('olahDataJurnalKuliah.urls',namespace='olahDataJurnalKuliah')),
    re_path(r'^olahDataMahasiswa/',include('olahDataMahasiswa.urls',namespace='olahDataMahasiswa')),
    re_path(r'^olahDataMatakuliah/',include('olahDataMatakuliah.urls',namespace='olahDataMatakuliah')),
    re_path(r'^olahDataNilai/',include('olahDataNilai.urls',namespace='olahDataNilai')),
    re_path(r'^olahDataRPS/',include('olahDataRPS.urls',namespace='olahDataRPS')),
    re_path(r'^presensiKuliah/',include('presensiKuliah.urls',namespace='presensiKuliah')),
    re_path(r'^rekapHasilKuliah/',include('rekapHasilKuliah.urls',namespace='rekapHasilKuliah')),
    re_path(r'^rekapKRS/',include('rekapKRS.urls',namespace='rekapKRS')),
    re_path(r'^rekapPresensi/',include('rekapPresensi.urls', namespace='rekapPresensi')),
    re_path(r'^rekapRPS/',include('rekapRPS.urls',namespace='rekapRPS')),
    re_path(r'^subPokokBahasan/',include('subPokokBahasan.urls',namespace='subPokokBahasan')),
    re_path(r'^tes/$',views.tes),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('',views.index, name='index')
]

backend/simprosis/olahDataMahasiswa/models.py
from django.db import models
from django.urls import reverse_lazy
from rps.models import userProfiles
from datetime import datetime
# Create your models here.
class mahasiswa(models.Model):
    listTahunMasuk = []
    for r in range((datetime.now().year-7),(datetime.now().year+1)):
        listTahunMasuk.append((r,r))
    # nik = models.OneToOneField(
    #     userProfiles, 
    #     on_delete=models.CASCADE, 
    #     unique=True,)
    npm = models.CharField(max_length=20,unique=True)
    tahunMasuk = models.IntegerField(choices=listTahunMasuk, blank=True, null=True)
    kelas = models.CharField(max_length=2, blank=True, null=True)
    
    list_agama = (
        ('islam','Islam'),
        ('katolik','Katolik'),
        ('kristen','Kristen'),
        ('hindu','Hindu'),
        ('budha','Budha'),
        ('konghucu','Konghucu')
    )
    list_kelamin = (
        ('Laki','Laki - Laki'),
        ('perempuan','Perempuan')
    )
    noKTP = models.IntegerField(null=True,blank=True)
    nama = models.CharField(max_length=50, null=True,blank=True)
    alamat = models.TextField(default='',null=True,blank=True)
    tanggalLahir = models.DateField(auto_now=False, auto_now_add=False,null=True,blank=True)
    jenisKelamin = models.CharField(max_length=10, choices=list_kelamin,null=True,blank=True)
    agama = models.CharField(max_length=50,choices=list_agama,null=True,blank=True)

    class Meta:
        verbose_name = "mahasiswa"
        verbose_name_plural = "mahasiswa"

    def __str__(self):
        return "{} - {}".format(self.npm, self.nama)

    def get_absolute_url(self):
        return reverse_lazy('olahDataMahasiswa:index')

backend/simprosis/olahDataMahasiswa/forms.py
from django import forms
from . models import mahasiswa

class mahasiswaForm(forms.ModelForm):

    class Meta:

        model = mahasiswa
        fields = [
            'npm',
            'tahunMasuk',
            'kelas',

            'noKTP',
            'nama',
            'alamat',
            'tanggalLahir',
            'jenisKelamin',
            'agama'
        ]
        labels = {
            'npm':'Nomor Induk/Pokok Mahasiswa',
            'tahunMasuk':'Tahun Masuk mahasiswa',
            'kelas':'Kelas',

            'noKTP':'Nomor KTP',
            'nama':'Nama Lengkap',
            'alamat':'Alamat KTP',
            'tanggalLahir':'Tanggal Lahir',
            'jenisKelamin':'Jenis Kelamin',
            'agama':'Agama'
        }
        widgets = {
            'npm':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Contoh : xx.xx.xx.xxxx'
                }
            ),
            'tahunMasuk':forms.Select(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Tahun masuk',
                    # 'type':'date'
                }
            ),
            'kelas':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'kelas : "A", "B", ...'
                }
            ),

            'noKTP':forms.NumberInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Masukkan Nomor KTP'
                }
            ),
            'nama':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Masukkan Nama Lengkap'
                }
            ),
            'alamat':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Masukkan alamat Sesuai KTP'
                }
            ),
            'tanggalLahir':forms.DateInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'type':'date'
                }
            ),
            'jenisKelamin':forms.Select(
                attrs={
                    'class':'form-control form-control-sm',
                }
            ),
            'agama':forms.Select(
                attrs={
                    'class':'form-control form-control-sm',
                }
            )
        }

backend/simprosis/olahDataMahasiswa/views.py
from django.shortcuts import render, redirect
from .forms import mahasiswaForm
from .models import mahasiswa
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
    CreateView
)
from django.core.exceptions import ObjectDoesNotExist
import openpyxl

# from tablib import Dataset
# from .resources import mahasiswaResource

# Create your views here.


class mahasiswaCreateView(CreateView):
    form_class = mahasiswaForm
    template_name = 'olahDataMahasiswa/create.html'
    extra_context = {
        'appGroup':'Operasional',
        'appName': 'Olah Data Mahasiswa',
    }
    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        # print(kwargs)
        return super().get_context_data(*args, **kwargs)


class mahasiswaUpdateView(UpdateView):
    model = mahasiswa
    form_class = mahasiswaForm
    template_name = 'olahDataMahasiswa/create.html'
    extra_context = {
        'appGroup':'Operasional',
        'appName': 'Olah Data Mahasiswa',
    }
    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        # print(kwargs)
        return super().get_context_data(*args, **kwargs)



class mahasiswaListView(ListView):
    model = mahasiswa
    template_name = 'olahDataMahasiswa/index.html'
    ordering =['npm']
    paginate_by = 10
    extra_context = {
        'appGroup':'Operasional',
        'appName': 'Olah Data Mahasiswa',
    }
    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        # print(kwargs)
        return super().get_context_data(*args, **kwargs)



class mahasiswaDeleteView(DeleteView):
    model = mahasiswa
    extra_context = {
        'appGroup':'Operasional',
        'appName': 'Olah Data Mahasiswa',
    }
    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        # print(kwargs)
        return super().get_context_data(*args, **kwargs)
    def get_success_url(self):
        return reverse_lazy('olahDataMahasiswa:index')



# def importDataMhs(request):
#     if request.method=='POST':
#         mahasiswa_resource = mahasiswaResource()
#         dataset = Dataset()
#         data_mhs_import = request.FILES['fileImport']

#         imported_data = dataset.load(data_mhs_import.read().decode('utf-8'),format='csv')
#         result = mahasiswa_resource.import_data(dataset, dry_run=True)

#         print(result.has_errors())
#         print(imported_data)

#         if not result.has_errors():
#             mahasiswa_resource.import_data(dataset, dry_run=False)
#     context = {
#         'appGroup':'Operasional',
#         'appName': 'Import Data Mahasiswa',
#         }
#     return render (request,'olahDataMahasiswa/importmhs.html',context)


def importDataMhs (request):
    context = {
            'appGroup': 'Operasional',
            'appName': 'Import Data Mahasiswa',
        }
    if request.method=='GET':
        
        return render (request,'olahDataMahasiswa/importmhs.html',context)
    
    else:
        data_mhs_import = request.FILES['fileImport']
        wb = openpyxl.load_workbook(data_mhs_import)
        # mendapatkan nama sheet
        worksheet = wb['Sheet1']
        print(worksheet)

        exel_data = list()
        dataSudahAda = list()
        # perulangan untuk baca row
        for row in worksheet.iter_rows(min_row=2, max_col=2):
            row_data = list()
            # perulangan untuk baca kolom
            for cell in row:
                isi = str(cell.value)
                row_data.append(isi.replace("'",""))
            # cek, create data di sini
            dataNpm = row_data[0]
            dataNama = row_data[1]
            try:
                mahasiswa.objects.get(npm=dataNpm)
                dataSudahAda.append(row_data)
                # pass
            except ObjectDoesNotExist:
                mahasiswa.objects.create(npm=dataNpm, nama=dataNama)
                exel_data.append(row_data)

            # print(row_data)
            # print('=======')
            # exel_data.append(row_data)
            
        context = {
            'appGroup': 'Operasional',
            'appName': 'Import Data Mahasiswa',
            
        }
        context['exel_data']=exel_data
        context['dataSudahAda']=dataSudahAda
        # print(exel_data)
        # print('----------------------------')
        # print(dataSudahAda)
        # print(context)
        return render (request,'olahDataMahasiswa/importmhs.html',context)




def index (request) :
    semua_mahasiswa = mahasiswa.objects.all()
    # print(semua_mahasiswa)
    context = {
        'appGroup':'Operasional',
        'appName': 'Olah Data Mahasiswa',
        'semua_mahasiswa':semua_mahasiswa
    }
    return render (request,'olahDataMahasiswa/index.html',context)

def create(request):
    formMahasiswa = mahasiswaForm(request.POST or None)
    # formMahasiswa.fields['nik'].queryset = userProfiles.objects.exclude(
    #     id__in=dosen.objects.all().values_list('nik_id',flat=True)
    # )
    if request.method=='POST':
        if formMahasiswa.is_valid():
            formMahasiswa.save()
            return redirect('olahDataMahasiswa:index')
    context = {
        'appGroup':'Operasional',
        'appName': 'Tambah Data Mahasiswa',
        'formMahasiswa':formMahasiswa
    }
    return render(request,'olahDataMahasiswa/create.html',context)

def delete(request,del_id):
    mahasiswa.objects.get(id=del_id).delete()
    return redirect('olahDataMahasiswa:index')

def update(request,update_id):
    dataMahasiswa = mahasiswa.objects.get(id=update_id)
    # formMahasiswa.fields['nik'].queryset = userProfiles.objects.exclude(
    #     id__in=dosen.objects.all().values_list('nik_id',flat=True)
    # )
    dataFormMahasiswa = {
        'nik':dataMahasiswa.nik,
        'npm':dataMahasiswa.npm,
        'tahunMasuk':dataMahasiswa.tahunMasuk,
        'kelas':dataMahasiswa.kelas
    }
    formMahasiswa = mahasiswaForm(request.POST or None, initial=dataFormMahasiswa, instance=dataMahasiswa)
    if request.method=='POST':
        if formMahasiswa.is_valid():
            formMahasiswa.save()
            return redirect('olahDataMahasiswa:index')
    context = {
        'appGroup':'Operasional',
        'appName': 'Tambah Data Mahasiswa',
        'formMahasiswa':formMahasiswa
    }
    return render(request,'olahDataMahasiswa/create.html',context)

backend/simprosis/olahDataMahasiswa/templates/olahDataMahasiswa/create.html
{% extends "base.html" %}
{% block content %}

    <a class="btn btn-outline-primary" href="{% url 'olahDataMahasiswa:import' %}">Import Mahasiswa</a>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button class="btn btn-primary" type="submit">Simpan</button>
    </form>
{% endblock content %}

backend/simprosis/olahDataMahasiswa/templates/olahDataMahasiswa/importmhs.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'olahDataMahasiswa:import' %}" method="post" enctype="multipart/form-data" required="required">
        {% csrf_token %}
        <input type="file" name="fileImport" >
        <button type="submit">Upload</button>
    </form>
    
    {% if dataSudahAda %}
        <br>
        <h5>Data gagal diimpor (sudah ada)</h5>
        {% for row in dataSudahAda %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    {% endif %}
        

    {% if exel_data %}
        <br>
        <h5>Data berhasil di impor :</h5>
        {% for row in exel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
    {% endif %}
    <br>
    <a class="btn btn-outline-primary" href="{% url 'olahDataMahasiswa:index' %}">Kembali ke daftar mahasiswa</a>
    
{% endblock content %}

backend/simprosis/olahDataMahasiswa/templates/olahDataMahasiswa/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<a class="btn btn-primary" href="{% url 'olahDataMahasiswa:create' %}">Tambah Mahasiswa</a>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>NPM</th>
                <th>Nama</th>
                <th>Tahun Masuk</th>
                <th>Kelas</th>
                <th>Ubah / Hapus</th>

            </tr>
        </thead>
        <tbody>
            {% for mhs in object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{mhs.npm}}</td>
                <td>{{mhs.nama}}</td>
                <td>{{mhs.tahunMasuk}}</td>
                <td>{{mhs.kelas}}</td>
                <td>
                    <a class="btn btn-outline-success" href="{% url 'olahDataMahasiswa:update' mhs.id %}">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="btn btn-outline-danger" href="{% url 'olahDataMahasiswa:delete' mhs.id %}">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>

    
<nav aria-label="...">
    <ul class="pagination">
        {% if is_paginated %}
       
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">First</a>
            </li>
            <li class="page-item ">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            {% endif %}
            
            {% for hal in paginator.page_range %}
                {% if hal is page_obj.number %}
                    <li class="page-item active">
                        <a class="page-link">{{hal}}<span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{hal}}">{{hal}}</a>
                    </li>
                {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>
            {% endif %}
        {% endif %}

    </ul>
</nav>

{% endblock content %}

backend/simprosis/olahDataMahasiswa/templates/olahDataMahasiswa/mahasiswa_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2></h2>
<hr>
<div>
    <form action="" method="post">{% csrf_token %}
        <p>Yakin ingin menghapus Mahasiswa "{{ object }}"?</p>
        <input type="submit" value="Yakin"/>
    </form>
</div>
{% endblock content %}