backend/simprosis/olahDataJurnalKuliah/urls.py
from django.urls import path, re_path, include
from django.conf.urls import url
from . views import (
    jurnalKuliahListView,
    jurnalKuliahCreateView,
    jurnalPerkuliahanCreateView,
    jurnalPerkuliahanUpdateView,
    jurnalKuliahDeleteView,
    jurnalKuliahDetailView,
    importPesertaKuliah
)

app_name='olahDataJurnalKuliah'
urlpatterns = [
    re_path(r'^$',jurnalKuliahListView.as_view(),name='jurnalKuliahList'),
    re_path(r'^createjurnal/$',jurnalKuliahCreateView.as_view(),name='jurnal-add'),
    re_path(r'^updatejurnal/(?P<pk>[0-9]+)$',jurnalPerkuliahanUpdateView.as_view(),name='jurnal-update'),
    re_path(r'^deletejurnal/(?P<pk>[0-9]+)$',jurnalKuliahDeleteView.as_view(),name='jurnal-delete'),
    re_path(r'^detailjurnal/(?P<pk>[0-9]+)$',jurnalKuliahDetailView.as_view(),name='detailjurnal'),
    re_path(r'^importPesertaKuliah/(?P<idJurnal>[0-9]+)$',importPesertaKuliah, name='importPesertaKuliah'),
]

backend/simprosis/rps/urls.py
#urls RPS
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name='rps'
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^submenurps/$',views.submenurps),
    re_path(r'^profile/$',views.profile,name='profile'),
    path('fakultas/',views.fakultasListView.as_view(),name='fakultasList'),
    re_path(r'^updatefakultas/(?P<pk>[0-9]+)$',views.fakProdiUpdateView.as_view(),name='fakultas-update'),
    re_path(r'^deletefakultas/(?P<pk>[0-9]+)$',views.fakultasDeleteView.as_view(),name='fakultas-delete'),
    re_path(r'^createfakultas$',views.fakProdiCreateView.as_view(),name='fakultas-add')
]

backend/simprosis/simprosis/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^rps/',include('rps.urls',namespace='rps')), #menghubungkan url rps dengan url project simprosis
    re_path(r'^biodataDosen/',include('biodataDosen.urls',namespace='biodataDosen')),
    re_path(r'^biodataMahasiswa/',include('biodataMahasiswa.urls',namespace='biodataMahasiswa')),
    re_path(r'^inputKRS/',include('inputKRS.urls',namespace='inputKRS')),
    re_path(r'^olahDataDosen/',include('olahDataDosen.urls', namespace='olahDataDosen')),
    re_path(r'^olahDataJurnalKuliah/',include('olahDataJurnalKuliah.urls',namespace='olahDataJurnalKuliah')),
    re_path(r'^olahDataMahasiswa/',include('olahDataMahasiswa.urls',namespace='olahDataMahasiswa')),
    re_path(r'^olahDataMatakuliah/',include('olahDataMatakuliah.urls',namespace='olahDataMatakuliah')),
    re_path(r'^olahDataNilai/',include('olahDataNilai.urls',namespace='olahDataNilai')),
    re_path(r'^olahDataRPS/',include('olahDataRPS.urls',namespace='olahDataRPS')),
    re_path(r'^presensiKuliah/',include('presensiKuliah.urls',namespace='presensiKuliah')),
    re_path(r'^rekapHasilKuliah/',include('rekapHasilKuliah.urls',namespace='rekapHasilKuliah')),
    re_path(r'^rekapKRS/',include('rekapKRS.urls',namespace='rekapKRS')),
    re_path(r'^rekapPresensi/',include('rekapPresensi.urls', namespace='rekapPresensi')),
    re_path(r'^rekapRPS/',include('rekapRPS.urls',namespace='rekapRPS')),
    re_path(r'^subPokokBahasan/',include('subPokokBahasan.urls',namespace='subPokokBahasan')),
    re_path(r'^tes/$',views.tes),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('',views.index, name='index')
]

backend/simprosis/subPokokBahasan/urls.py
from django.urls import path, re_path, include
from django.conf.urls import url
from . views import (
    jurnalKuliahListView, 
    jurnalKuliahDetailView,
    detilJurnalKuliahCreateView,
    detilJurnalKuliahFromRPSCreateView,
    detilJurnalKuliahUpdateView,
    detilJurnalKuliahDeleteView,
    detilRPSListView,
    presensiDetailView,
    importPesertaKuliah,
    buatPresensi
)

app_name='subPokokBahasan'
urlpatterns = [
    # tambahkan url presensi ke app presensiKuliah
    re_path(r'^$', jurnalKuliahListView.as_view(),name='index'),
    re_path(r'^presensi/(?P<pk>[0-9]+)/(?P<id_dtJurnal>[0-9]+)$',presensiDetailView.as_view(),name='presensi'),
    re_path(r'^presensi/buatPresensi/(?P<idJurnal>[0-9]+)/(?P<id_dtJurnal>[0-9]+)$',buatPresensi, name='buatPresensi'),
    re_path(r'^presensi/importPesertaKuliah/(?P<id_dtjurnal>[0-9]+)$',importPesertaKuliah,name='importPesertaKuliah'),
    re_path(r'^(?P<pk>[0-9]+)$',jurnalKuliahDetailView.as_view(), name='detiljurnalkuliah'),
    re_path(r'^createdetiljurnalfromrps/(?P<id_jurnal>[0-9]+)/(?P<id_rps>[0-9]+)$',detilJurnalKuliahFromRPSCreateView.as_view(),name='createdetiljurnalfromrps'),
    re_path(r'^createdetiljurnal/(?P<id_jurnal>[0-9]+)$',detilJurnalKuliahCreateView.as_view(),name='createdetiljurnal'),
    re_path(r'^detiljurnalfromrps/(?P<id_rps>[0-9]+)/(?P<id_jurnal>[0-9]+)$',detilRPSListView.as_view(),name='detiljurnalfromrps'),
    re_path(r'^updatedetiljurnal/(?P<pk>[0-9]+)$',detilJurnalKuliahUpdateView.as_view(),name='updatedetiljurnal'),
    re_path(r'^deletedetiljurnal/(?P<pk>[0-9]+)$',detilJurnalKuliahDeleteView.as_view(),name='deletedetiljurnal'),

]

backend/simprosis/subPokokBahasan/models.py
from django.db import models
from olahDataMahasiswa.models import mahasiswa
from olahDataJurnalKuliah.models import detilJurnalKuliah

# Create your models here.
# class presensi(models.Model):
#     """Model definition for presensi."""
#     # ambil dari detil jurnal
#     # ambil dari mahasiswa
#     # TODO: Define fields here
#     jurnalPerkuliahan = models.ForeignKey(detilJurnalKuliah, on_delete=models.CASCADE, null=True)
#     npm = models.ForeignKey(mahasiswa, on_delete=models.CASCADE)
#     presensi = models.BooleanField(default=False)

#     class Meta:
#         """Meta definition for presensi."""

#         verbose_name = 'presensi'
#         verbose_name_plural = 'presensi'

#     def __str__(self):
#         return "{}-{}".format(self.jurnalPerkuliahan, self.npm)

backend/simprosis/subPokokBahasan/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView
)
from olahDataMatakuliah.models import matakuliah
from olahDataJurnalKuliah.models import jurnalKuliah,detilJurnalKuliah, pesertaKuliah
from olahDataRPS.models import rps, detilRPS
from .forms import detilJurnalKuliahForm, updatedetilJurnalKuliahForm
from presensiKuliah.models import presensi
from olahDataMahasiswa.models import mahasiswa
import openpyxl
# Create your views here.

# menampilkan RPS dengan kode mk yang sama pada jurnal kuliah

class detilRPSListView(ListView): #rubah menjadi detailView
    model = detilRPS
    template_name = 'subPokokBahasan/listRpsUntukJurnal.html'
    # paginate_by = 10
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Pilih Pertemuan untuk jurnal kuliah', 
    }

    def get_queryset(self):
        if not self.kwargs['id_rps'] == None:
            self.queryset=self.model.objects.filter(idRps_id=self.kwargs['id_rps'])
        return super().get_queryset()

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        print (kwargs)
        return super().get_context_data(*args, **kwargs)



class jurnalKuliahListView(ListView):
    model = jurnalKuliah
    template_name = 'subPokokBahasan/jurnalKuliah_list.html'
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Sub Pokok Bahasan - Pilih daftar jurnal kuliah', 
    }

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


class jurnalKuliahDetailView(DetailView):
    model = jurnalKuliah
    template_name = 'subPokokBahasan/jurnalKuliah_detail.html'
    extra_context ={
        'appGroup':'Presensi',
        'appName':'Sub Pokok Bahasan', 
    }

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        idJurnal = jurnalKuliah.objects.values_list('mk_id', flat=True).get(id=self.kwargs['pk'])
        self.kwargs.update({'idJurnal':idJurnal})
        matkul = matakuliah.objects.all().get(id=self.kwargs['idJurnal'])
        self.kwargs.update({'matkul':matkul})

        detilJurnal=detilJurnalKuliah.objects.filter(jurnal_id=self.kwargs['pk'])
        self.kwargs.update({'detilJurnal':detilJurnal}) 

        # ambil id_rps yang memiliki kode matakuliah 
        # jika ada id_rps maka
        try:
            id_rps=rps.objects.values_list('id',flat=True).get(kodemk_id=self.object.mk_id)
        # except id_rps.DoesNotExist:
        except ObjectDoesNotExist:
            id_rps = None
        # id_rps=rps.objects.values_list('id',flat=True).get(kodemk_id=self.object.mk_id)
        self.kwargs.update({'id_rps':id_rps})

        kwargs = self.kwargs
        print(kwargs)
        print('----------')
        print(kwargs['matkul'])
        print('----------')
        print(self.object.mk_id)
        return super().get_context_data(*args, **kwargs)



class detilJurnalKuliahCreateView(CreateView):
    form_class = detilJurnalKuliahForm
    template_name = 'subPokokBahasan/createdetilJurnalKualiah.html'
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Tambah Pokok Bahasan', 
    }

    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        print('dari get_context_data')
        print(kwargs)
        return super().get_context_data(*args, **kwargs)

    def get_initial(self, *args, **kwargs):
        jurnal = get_object_or_404(jurnalKuliah,id=self.kwargs['id_jurnal'])
        print('dari get initial')
        print (kwargs)
        return{
            'jurnal':jurnal
        }


class detilJurnalKuliahFromRPSCreateView(CreateView):
    form_class = detilJurnalKuliahForm
    template_name = 'subPokokBahasan/createdetilJurnalKualiah.html'
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Tambah Pokok Bahasan', 
    }

    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        print('dari get_context_data')
        print(kwargs)
        return super().get_context_data(*args, **kwargs)

    def get_initial(self, *args, **kwargs):
        jurnal = get_object_or_404(jurnalKuliah,id=self.kwargs['id_jurnal'])

        # id_rps=rps.objects.values_list('id',flat=True).get(kodemk_id=self.object.mk_id)
        # ambil isi pertemuan dari detilRPS berdasar id detilRPS
        pertemuan = detilRPS.objects.values_list('pertemuan', flat=True).get(id=self.kwargs['id_rps'])

        # ambil isi materiBelajar dari detilRPS berdasar id detilRPS
        materiBelajar = detilRPS.objects.values_list('materiBelajar', flat=True).get(id=self.kwargs['id_rps'])
        
        # ambil isi bentukMetodeBelajar dari detilRPS berdasar id detilRPS
        bentukMetodeBelajar = detilRPS.objects.values_list('bentukMetodeBelajar', flat=True).get(id=self.kwargs['id_rps'])

        print('dari get initial')
        print (kwargs)
        print('=============')
        print(jurnal)
        print(pertemuan)
        return{
            'jurnal':jurnal,
            'pertemuan':pertemuan,
            'materi':materiBelajar,
            'metode':bentukMetodeBelajar
        }


class detilJurnalKuliahUpdateView(UpdateView):
    model = detilJurnalKuliah
    form_class = updatedetilJurnalKuliahForm
    template_name = 'subPokokBahasan/createdetilJurnalKualiah.html'
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Rubah Pokok Bahasan', 
    }

    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        print(kwargs)
        return super().get_context_data(*args, **kwargs)

    # def get_initial(self):
    #     jurnal = get_object_or_404(jurnalKuliah,id=self.kwargs['id_jurnal'])
    #     return{
    #         'jurnal':jurnal
    #     }



class detilJurnalKuliahDeleteView(DeleteView):
    model = detilJurnalKuliah
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Hapus Pokok Bahasan', 
    }

    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        # print(kwargs)
        return super().get_context_data(*args, **kwargs)
    
    def get_success_url(self):
        jurnal = self.object.jurnal
        return reverse_lazy('subPokokBahasan:detiljurnalkuliah', kwargs={'pk':jurnal.id})


# UNTUK PRESENSI

class presensiDetailView(DetailView):
    model = jurnalKuliah
    template_name = 'subPokokBahasan/presensi_form.html'
    extra_context = {
        'appGroup':'Presensi',
        'appName':'Presensi kuliah', 
    }

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)

        dataKuliah = detilJurnalKuliah.objects.all().get(id=self.kwargs['id_dtJurnal'])
        self.kwargs.update({'dataKuliah':dataKuliah})

        pesertaKuliah = presensi.objects.filter(
            jurnalPerkuliahan_id=self.kwargs['id_dtJurnal']
        ).order_by(
            '-presensi',
            '-presenceDate'
        ).values(
            'npm__npm',
            'npm__nama',
            'presensi',
            'presenceDate'
        )
        self.kwargs.update({'pesertaKuliah':pesertaKuliah})

        jumlahKehadiran = presensi.objects.filter(
            jurnalPerkuliahan_id=self.kwargs['id_dtJurnal'],
            presensi=True
        ).count()
        self.kwargs.update({'jumlahKehadiran':jumlahKehadiran})

        kwargs = self.kwargs
        # print(kwargs)
        # print(kwargs['jumlahKehadiran'])
        return super().get_context_data(*args, **kwargs)



def index(request):
    context = {
        'appGroup':'Presensi',
        'appName':'SuB Pokok Bahasan',
    }
    return render(request,'subPokokBahasan/index.html',context)



def importPesertaKuliah(request,id_dtjurnal):
    context = {
            'appGroup': 'Presensi',
            'appName': 'Import Mahasiswa Peserta Kuliah',
            'id_dtJurnal':id_dtjurnal
        }
    if request.method=='GET':
        return render (request,'subPokokBahasan/importPesertaKuliah.html',context)
    else:
        dataFile = request.FILES['fileImport']
        wb = openpyxl.load_workbook(dataFile)
        sheets = wb.sheetnames
        print(sheets)
        worksheet = wb[sheets[0]]

        exel_data=list()
        dataSudahAda = list()
        mhsBelumAda = list()
        # perulangan row 
        for row in worksheet.iter_rows(min_row=2, max_col=2):
            row_data = list()
            # perulangan kolom
            for cell in row:
                isi = str(cell.value)
                row_data.append(isi.replace("'",""))
            dataNpm = row_data[0]
            print(dataNpm)
            try:
                # ambil id mahasiswa
                idMhs = mahasiswa.objects.values_list('id', flat=True).get(npm=dataNpm)
                
                try:    
                    # cek id mahasiswa tersebut sudah ada di tabel presensi apa belum 
                    # dengan jurnalPerkuliahan_id=id_dtJurnal
                    presensi.objects.get(npm_id=idMhs,jurnalPerkuliahan_id=id_dtjurnal)
                    dataSudahAda.append(row_data)
                except ObjectDoesNotExist:
                    # jika belum tambahkan
                    presensi.objects.create(
                        jurnalPerkuliahan_id=id_dtjurnal,
                        npm_id=idMhs
                    )
                    exel_data.append(row_data)
                    # pass
            except ObjectDoesNotExist:

backend/simprosis/subPokokBahasan/templates/subPokokBahasan/createdetilJurnalKualiah.html
{% extends "base.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-primary" type="submit">Simpan</button>
</form>
{% endblock content %}

backend/simprosis/subPokokBahasan/templates/subPokokBahasan/importPesertaKuliah.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'subPokokBahasan:importPesertaKuliah' id_dtJurnal %}" method="post" enctype="multipart/form-data" required="required">
        {% csrf_token %}
        <input type="file" name="fileImport" >
        <button type="submit">Upload</button>
    </form>
    <h1>{{id_dtJurnal}}</h1>
    {% if dataSudahAda %}
        <br>
        <h5>Data gagal diimpor (sudah ada)</h5>
        {% for row in dataSudahAda %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    {% endif %}
        

    {% if exel_data %}
        <br>
        <h5>Data berhasil diimpor :</h5>
        {% for row in exel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
    {% endif %}

    {% if mhsBelumAda %}
        <br>
        <h5>Data Mahasiswa belum ada :</h5>
        {% for row in mhsBelumAda %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
    {% endif %}
    <br>
    <a class="btn btn-outline-primary" href="#">Kembali ke daftar mahasiswa</a>
    
{% endblock content %}

backend/simprosis/subPokokBahasan/templates/subPokokBahasan/jurnalKuliah_detail.html
{% extends "base.html" %}
<!-- {% load qr_code %} -->
{% block content %}
<!-- <h1>detail Jurnal Kuliah</h1> -->
<!-- {{object}} -->
<div class="table table-responsive">
    <table class="table">
        <tr>
            <td colspan="4" align="center"><h5>JURNAL PERKULIAHAN</h5></td>
        </tr>
        <tr>
            <td>Matakuliah</td> 
            <td>: {{object.mk}}</td>
            <td>Tingkat /  Kelas</td>
            <td>: {{object.kelas}}</td>
        </tr>
        <tr>
            <td>Dosen</td>
            <td>: {{object.dosenPengajar}}</td>
            <td>Semester</td>
            <td>: {{matkul.semester}}</td>
        </tr>
    </table>
</div>
<div class="card">
    <div class="card-header">
        Rincian Jurnal Perkuliahan
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>Pert</td>
                        <td>Tanggal</td>
                        <td>Mulai</td>
                        <td>Selesai</td>
                        <td>Materi</td>
                        <td>Metode</td>
                        <td>Presensi</td>
                        <td>Edit / Hapus</td>
                    </tr>
                </thead>
                <tbody>
                    {% for dtJurnal in detilJurnal %}
                        <tr>
                            <td>{{dtJurnal.pertemuan}}</td>
                            <td>{{dtJurnal.tanggal}}</td>
                            <td>{{dtJurnal.jamMulai}}</td>
                            <td>{{dtJurnal.jamSelesai}}</td>
                            <td>{{dtJurnal.materi|truncatewords:2}}</td>
                            <td>{{dtJurnal.metode|truncatewords:2}}</td>
                            <td><a class="btn btn-outline-info" href="{% url 'subPokokBahasan:presensi' object.pk dtJurnal.id %}">
                                    <i class="fa fa-qrcode"></i>
                                    <!-- diarahkan ke app presensiKuliah -->
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-outline-success" href="{% url 'subPokokBahasan:updatedetiljurnal' dtJurnal.id %}">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a class="btn btn-outline-danger" href="{% url 'subPokokBahasan:deletedetiljurnal' dtJurnal.id %}">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="7">Belum ada...</td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        <a class="btn btn-primary btn-block" href="{% url 'subPokokBahasan:createdetiljurnal' object.id %}">Tambah Pertemuan</a>
        
        {% if id_rps %}
            <a class="btn btn-info btn-block" href="{% url 'subPokokBahasan:detiljurnalfromrps' id_rps object.id %}">Tambah Pertemuan dari RPS</a>
        {% else %}
            <a class="btn btn-danger btn-block" href="{% url 'olahDataRPS:index' %}">RPS Belum ada, klik tombol ini untuk menambah RPS</a>
        {% endif %}
            
    </div>
    <a class="btn btn-outline-primary btn-block" href="{% url 'subPokokBahasan:index' %}">Kembali ke daftar jurnal</a>
</div>
{% endblock content %}

backend/simprosis/subPokokBahasan/templates/subPokokBahasan/jurnalKuliah_list.html
{% extends "base.html" %}
{% block content %}
<!-- <a class="btn btn-primary" href="{% url 'olahDataJurnalKuliah:jurnal-add' %}">Tambah Jurnal</a> -->
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Matakuliah</th>
                <th>Tahun</th>
                <th>Smt</th>
                <th>Dosen</th>
                <th>Kelas</th>
            </tr>
        </thead>
        <tbody>
            {% for jurnal in object_list %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>
                        <a href="{% url 'subPokokBahasan:detiljurnalkuliah' jurnal.pk %}">{{jurnal.mk}}</a>
                        
                    </td>
                    <td>{{jurnal.tahunAjaran}}</td>
                    <td>{{jurnal.semester}}</td>
                    <td>{{jurnal.dosenPengajar}}</td>
                    <td>{{jurnal.kelas}}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">Belum ada jurnal</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

backend/simprosis/subPokokBahasan/templates/subPokokBahasan/listRpsUntukJurnal.html
{% extends "base.html" %}
{% block content %}
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Pertemuan</th>
                    <th>Materi</th>
                    <th>Metode</th>
                    <th>Gunakan</th>
                </tr>
            </thead>
            <tbody>
                
                {% for dtRps in object_list %}
                <tr>
                    <td>{{dtRps.pertemuan}}</td>
                    <td>{{dtRps.materiBelajar|truncatewords:3}}</td>
                    <td>{{dtRps.bentukMetodeBelajar|truncatewords:3}}</td>
                    <td>
                        <a class="btn btn-outline-success" 
                        href="{% url 'subPokokBahasan:createdetiljurnalfromrps' id_jurnal dtRps.id %}">
                        <i class="fa fa-clone"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                    <tr>
                        <td colspan="4"> Belum ada...</td>
                    </tr>
                {% endfor %}
                    
            </tbody>
        </table>
    </div>
{% endblock content %}

backend/simprosis/subPokokBahasan/templates/subPokokBahasan/presensi_form.html
{% extends "base.html" %}
{% block content %}
{% load qr_code %}
<div class="table table-responsive">
    <div class="card">
        <div class="card-body">
            <table class="table">
                <tr>
                    <td><b>Matakuliah</b> </td>
                    <td>{{object.mk}}</td>
                    <td><b>Kelas</b></td>
                    <td>{{object.kelas}}</td>
                    <td><b>Jam</b></td>
                    <td>{{dataKuliah.jamMulai}} - {{dataKuliah.jamSelesai}}</td>
                    
                </tr>
                <tr>
                    <td><b>Dosen</b></td>
                    <td>{{object.dosenPengajar}}</td>
                    <td><b>Materi</b></td>
                    <td colspan="3">{{dataKuliah.materi|truncatewords:20}}</td>
                </tr>
            </table>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-sm-7">
        <div class="card border-primary">
            <div class="card-header">
                Jumlah Mahasiswa : <b>{{pesertaKuliah|length}}</b>. Hadir : <b>{{jumlahKehadiran}}</b>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <th>NPM</th>
                            <th>Nama</th>
                            <th>Hadir</th>
                            <th>Waktu</th>
                        </thead>
                        <tbody>
                            {% for data in pesertaKuliah %}
                                <tr>
                                    <td>{{data.npm__npm}}</td>
                                    <td>{{data.npm__nama}}</td>
                                    <td>
                                        
                                        {% if data.presensi == True %}
                                            <i class="fa fa-check" style="color:green"></i>
                                        {% else %}
                                            <i class="fa fa-ban" style="color:red"></i>
                                        {% endif %}   
                                        
                                    </td>
                                    <td>{{data.presenceDate}}</td>
                                </tr>
                            {% empty %}
                            <tr>
                                <td colspan="4">Belum ada</td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
                <a class="btn btn-primary btn-block" href="{% url 'subPokokBahasan:buatPresensi' object.pk id_dtJurnal %}">Tambah Peserta Kuliah</a>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <div class="card">
            <div class="card-body">
                {% qr_from_text id_dtJurnal size="L" border=6 %}
            </div>
        </div>
    </div>
    
</div>

{% endblock content %}