backend/simprosis/olahDataJurnalKuliah/urls.py
from django.urls import path, re_path, include
from django.conf.urls import url
from . views import (
    jurnalKuliahListView,
    jurnalKuliahCreateView,
    jurnalPerkuliahanCreateView,
    jurnalPerkuliahanUpdateView,
    jurnalKuliahDeleteView,
    jurnalKuliahDetailView,
    importPesertaKuliah
)

app_name='olahDataJurnalKuliah'
urlpatterns = [
    re_path(r'^$',jurnalKuliahListView.as_view(),name='jurnalKuliahList'),
    re_path(r'^createjurnal/$',jurnalKuliahCreateView.as_view(),name='jurnal-add'),
    re_path(r'^updatejurnal/(?P<pk>[0-9]+)$',jurnalPerkuliahanUpdateView.as_view(),name='jurnal-update'),
    re_path(r'^deletejurnal/(?P<pk>[0-9]+)$',jurnalKuliahDeleteView.as_view(),name='jurnal-delete'),
    re_path(r'^detailjurnal/(?P<pk>[0-9]+)$',jurnalKuliahDetailView.as_view(),name='detailjurnal'),
    re_path(r'^importPesertaKuliah/(?P<idJurnal>[0-9]+)$',importPesertaKuliah, name='importPesertaKuliah'),
]

backend/simprosis/rps/urls.py
#urls RPS
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name='rps'
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^submenurps/$',views.submenurps),
    re_path(r'^profile/$',views.profile,name='profile'),
    path('fakultas/',views.fakultasListView.as_view(),name='fakultasList'),
    re_path(r'^updatefakultas/(?P<pk>[0-9]+)$',views.fakProdiUpdateView.as_view(),name='fakultas-update'),
    re_path(r'^deletefakultas/(?P<pk>[0-9]+)$',views.fakultasDeleteView.as_view(),name='fakultas-delete'),
    re_path(r'^createfakultas$',views.fakProdiCreateView.as_view(),name='fakultas-add')
]

backend/simprosis/simprosis/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^rps/',include('rps.urls',namespace='rps')), #menghubungkan url rps dengan url project simprosis
    re_path(r'^biodataDosen/',include('biodataDosen.urls',namespace='biodataDosen')),
    re_path(r'^biodataMahasiswa/',include('biodataMahasiswa.urls',namespace='biodataMahasiswa')),
    re_path(r'^inputKRS/',include('inputKRS.urls',namespace='inputKRS')),
    re_path(r'^olahDataDosen/',include('olahDataDosen.urls', namespace='olahDataDosen')),
    re_path(r'^olahDataJurnalKuliah/',include('olahDataJurnalKuliah.urls',namespace='olahDataJurnalKuliah')),
    re_path(r'^olahDataMahasiswa/',include('olahDataMahasiswa.urls',namespace='olahDataMahasiswa')),
    re_path(r'^olahDataMatakuliah/',include('olahDataMatakuliah.urls',namespace='olahDataMatakuliah')),
    re_path(r'^olahDataNilai/',include('olahDataNilai.urls',namespace='olahDataNilai')),
    re_path(r'^olahDataRPS/',include('olahDataRPS.urls',namespace='olahDataRPS')),
    re_path(r'^presensiKuliah/',include('presensiKuliah.urls',namespace='presensiKuliah')),
    re_path(r'^rekapHasilKuliah/',include('rekapHasilKuliah.urls',namespace='rekapHasilKuliah')),
    re_path(r'^rekapKRS/',include('rekapKRS.urls',namespace='rekapKRS')),
    re_path(r'^rekapPresensi/',include('rekapPresensi.urls', namespace='rekapPresensi')),
    re_path(r'^rekapRPS/',include('rekapRPS.urls',namespace='rekapRPS')),
    re_path(r'^subPokokBahasan/',include('subPokokBahasan.urls',namespace='subPokokBahasan')),
    re_path(r'^tes/$',views.tes),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('',views.index, name='index')
]

backend/simprosis/olahDataJurnalKuliah/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory
from . models import jurnalKuliah, detilJurnalKuliah

class jurnalKuliahForm(forms.ModelForm):
    """Form definition for jurnalKuliah."""

    class Meta:
        """Meta definition for jurnalKuliahform."""

        model = jurnalKuliah
        fields = [
            'mk',
            'tahunAjaran',
            'semester',
            'dosenPengajar',
            'ruang',
            'pjmk',
            'kelas'
        ]
        labels ={
            'mk':'Matakuliah',
            'tahunAjaran':'Tahun Ajaran',
            'semester':'Semester',
            'dosenPengajar':'Dosen Pengampu',
            'ruang':'Ruang Kuliah',
            'pjmk':'PJMK',
            'kelas':'Kelas'
        }
        widgets = {
            'mk':forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'tahunAjaran':forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'semester':forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'dosenPengajar':forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'ruang':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Ruang Kelas'
                }
            ),
            'pjmk':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'PJMK'
                }
            ),
            'kelas':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Kelas'
                }
            )
        }


class detilJurnalKuliahForm(forms.ModelForm):
    """Form definition for detilJurnalKuliah."""

    class Meta:
        """Meta definition for detilJurnalKuliahform."""

        model = detilJurnalKuliah
        exclude=()
        # fields = [
        #     'jurnal',
        #     'pertemuan',
        #     'tanggal',
        #     'jamMulai',
        #     'jamSelesai',
        #     'materi',
        #     'metode'
        # ]
        labels ={
            'jurnal':'Jurnal',
            'pertemuan':'Pertemuan',
            'tanggal':'Tanggal Kuliah',
            'jamMulai':'Jam Mulai',
            'jamSelesai':'Jam Selesai',
            'materi':'Materi',
            'metode':'Metode'
        }
        widgets = {
            'jurnal':forms.Select(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'pertemuan':forms.NumberInput(
                attrs={
                    'class':'form-control form-control-sm'
                }
            ),
            'tanggal':forms.DateInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'type':'date'
                }
            ),
            'jamMulai':forms.DateInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'type':'time'
                }
            ),
            'jamSelesai':forms.DateInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'type':'time'
                }
            ),
            'materi':forms.Textarea(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Materi'
                }
            ),
            'metode':forms.TextInput(
                attrs={
                    'class':'form-control form-control-sm',
                    'placeholder':'Metode Belajar'
                }
            )
        }

JurnalFormset = inlineformset_factory(jurnalKuliah,detilJurnalKuliah,form=detilJurnalKuliahForm,extra=1)

backend/simprosis/olahDataJurnalKuliah/views.py
from django.shortcuts import render
from django.db import transaction
from django.urls import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, DetailView
from . forms import (
        jurnalKuliahForm, 
        detilJurnalKuliahForm, 
        JurnalFormset, 
        jurnalKuliahForm
    )
from . models import jurnalKuliah, detilJurnalKuliah, pesertaKuliah
from olahDataMahasiswa.models import mahasiswa
import openpyxl


# Create your views here.
def index (request):
    context = {
        'appGroup' : 'Operasional',
        'appName' : 'Olah Data Jurnal Kuliah',
    }
    return render(request,'olahDataJurnalKuliah/index.html',context)


class jurnalKuliahListView(ListView):
    model = jurnalKuliah
    ordering =['-id']
    extra_context = {
        'appGroup' : 'Operasional',
        'appName' : 'Olah Data Jurnal Kuliah',
    }
    
    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


class jurnalKuliahCreateView(CreateView):
    form_class = jurnalKuliahForm
    template_name = 'olahDataJurnalKuliah/jurnalkuliah_form.html'
    extra_context = {
        'appGroup':'Operasional',
        'appName':'Olah Data Jurnal Kuliah', 
    }

    def get_context_data(self,*args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        # print(kwargs)
        return super().get_context_data(*args, **kwargs)
    # model = jurnalKuliah

    # fields = [
    #     'mk',
    #     'tahunAjaran',
    #     'semester',
    #     'dosenPengajar',
    #     'ruang',
    #     'pjmk'
    # ]


class jurnalPerkuliahanCreateView(CreateView):
    model = jurnalKuliah
    fields = [
        'mk',
        'tahunAjaran',
        'semester',
        'dosenPengajar',
        'ruang',
        'pjmk'
    ]
    success_url = reverse_lazy('olahDataJurnalKuliah:jurnalKuliahList')

    def get_context_data(self, **kwargs):
        data = super(jurnalPerkuliahanCreateView, self).get_context_data(**kwargs)
        if self.request.POST :
            data['dtlJurnalKuliah']=JurnalFormset(self.request.POST)
        else:
            data['dtlJurnalKuliah']=JurnalFormset()
        return data
    
    def form_valid(self, form):
        context = self.get_context_data()
        dtlJurnalKuliah = context['dtlJurnalKuliah']
        with transaction.atomic():
            self.object = form.save()
            if dtlJurnalKuliah.is_valid():
                dtlJurnalKuliah.instance=self.object
                dtlJurnalKuliah.save()
        return super(jurnalPerkuliahanCreateView,self).form_valid(form)


class jurnalKuliahUpdateView(UpdateView):
    model = jurnalKuliah
    success_url = reverse_lazy('olahDataJurnalKuliah:jurnalKuliahList')
    fields = [
        'mk',
        'tahunAjaran',
        'semester',
        'dosenPengajar',
        'ruang',
        'pjmk'
    ]


class jurnalPerkuliahanUpdateView(UpdateView):
    form_class = jurnalKuliahForm
    model = jurnalKuliah
    template_name = 'olahDataJurnalKuliah/jurnalkuliah_form.html'
    extra_context = {
        'appGroup':'Operasional',
        'appName':'Rubah Data Jurnal Kuliah', 
    }
    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

    # fields = [
    #     'mk',
    #     'tahunAjaran',
    #     'semester',
    #     'dosenPengajar',
    #     'ruang',
    #     'pjmk'
    # ]
    success_url = reverse_lazy('olahDataJurnalKuliah:jurnalKuliahList')
    
    # def get_context_data(self,**kwargs):
    #     data = super(jurnalPerkuliahanUpdateView, self).get_context_data(**kwargs)
    #     if self.request.POST :
    #         data['dtlJurnalKuliah']=JurnalFormset(self.request.POST, instance=self.object)
    #     else:
    #         data['dtlJurnalKuliah']=JurnalFormset(instance = self.object)
    #     return data
    
    # def form_valid(self, form):
    #     context = self.get_context_data()
    #     dtlJurnalKuliah = context['dtlJurnalKuliah']
    #     with transaction.atomic():
    #         self.object = form.save()
    #         if dtlJurnalKuliah.is_valid():
    #             dtlJurnalKuliah.instance=self.object
    #             dtlJurnalKuliah.save()
    #     return super(jurnalPerkuliahanUpdateView,self).form_valid(form)
    

class jurnalKuliahDeleteView(DeleteView):
    model = jurnalKuliah
    success_url = reverse_lazy('olahDataJurnalKuliah:jurnalKuliahList')


class jurnalKuliahDetailView(DetailView):
    model = jurnalKuliah
    template_name = 'olahDataJurnalKuliah/jurnalKuliah_detail.html'
    extra_context = {
        'appGroup':'Operasional',
        'appName':'Detil Data Jurnal Kuliah', 
    }

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)

        # tampilkan data peserta kuliah
        pstKuliah = pesertaKuliah.objects.filter(
            jurnal_id=self.kwargs['pk']
            ).values(
                'peserta__npm',
                'peserta__nama'
            )
        self.kwargs.update({'pstKuliah':pstKuliah})

        kwargs = self.kwargs
        print(self.object)
        return super().get_context_data(*args, **kwargs)


def importPesertaKuliah(request,idJurnal):
    context = {
            'appGroup': 'Presensi',
            'appName': 'Import Mahasiswa Peserta Kuliah',
            'idJurnal':idJurnal
        }
    if request.method=='GET':
        return render (request,'olahDataJurnalKuliah/importPesertaKuliah.html',context)
    else:
        dataFile = request.FILES['fileImport']
        wb = openpyxl.load_workbook(dataFile)
        sheets = wb.sheetnames
        print(sheets)
        worksheet = wb[sheets[0]]

        exel_data=list()
        dataSudahAda = list()
        mhsBelumAda = list()
        # perulangan row 
        for row in worksheet.iter_rows(min_row=2, max_col=2):
            row_data = list()
            # perulangan kolom
            for cell in row:
                isi = str(cell.value)
                row_data.append(isi.replace("'",""))
            dataNpm = row_data[0]
            print(dataNpm)
            try:
                # ambil id mahasiswa
                idMhs = mahasiswa.objects.values_list('id', flat=True).get(npm=dataNpm)
                
                try:    
                    # cek id mahasiswa tersebut sudah ada di tabel pesertaKuliah apa belum 
                    # dengan idJurnalKuliah=idJurnal
                    pesertaKuliah.objects.get(peserta_id=idMhs,jurnal_id=idJurnal)
                    dataSudahAda.append(row_data)
                except ObjectDoesNotExist:
                    # jika belum tambahkan
                    pesertaKuliah.objects.create(
                        jurnal_id=idJurnal,
                        peserta_id=idMhs
                    )
                    exel_data.append(row_data)
                    # pass
            except ObjectDoesNotExist:
                # gagal diimport, karena data mahasiswa belum ditambahkan, 
                mhsBelumAda.append(row_data)
                # pass
        # asdda
        context['exel_data']=exel_data
        context['dataSudahAda']=dataSudahAda
        context['mhsBelumAda']=mhsBelumAda

        return render (request,'olahDataJurnalKuliah/importPesertaKuliah.html',context)

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/detiljurnalkuliah_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2></h2>
<hr>
<div>
    <form action="" method="post">{% csrf_token %}
        <p>Yakin ingin menghapus Rincian Jurnal "{{ object }}"?</p>
        <input type="submit" value="Yakin"/>
    </form>
</div>
{% endblock content %}

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/importPesertaKuliah.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'olahDataJurnalKuliah:importPesertaKuliah' idJurnal %}" method="post" enctype="multipart/form-data" required="required">
        {% csrf_token %}
        <input type="file" name="fileImport" >
        <button type="submit">Upload</button>
    </form>
    <h1>{{idJurnal}}</h1>
    {% if dataSudahAda %}
        <br>
        <h5>Data gagal diimpor (sudah ada)</h5>
        {% for row in dataSudahAda %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
    {% endif %}
        

    {% if exel_data %}
        <br>
        <h5>Data berhasil diimpor :</h5>
        {% for row in exel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
    {% endif %}

    {% if mhsBelumAda %}
        <br>
        <h5>Data Mahasiswa belum ada :</h5>
        {% for row in mhsBelumAda %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}  
    {% endif %}
    <br>
    <a class="btn btn-outline-primary" href="{% url 'olahDataJurnalKuliah:detailjurnal' idJurnal %}">Kembali ke Detil Jurnal</a>
    
{% endblock content %}

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="text-center">
        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{% static 'img/undraw_posting_photo.svg' %}" alt="">
    </div>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod minus asperiores deleniti? Quas laboriosam at ipsam aperiam sed consectetur, illum ducimus similique officia tempora optio, suscipit enim. Debitis, exercitationem earum!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut distinctio, reiciendis fuga voluptatem explicabo consequatur optio omnis corporis dolore eius? Quod nobis ea rerum quaerat, rem laborum fugit architecto necessitatibus.
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur facere, cumque dolorum laboriosam tempore veritatis quo, aspernatur sapiente at quae quidem obcaecati deserunt reprehenderit inventore iure tempora laborum molestias esse.
    </p>
{% endblock content %}
    

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/jurnalKuliah_detail.html
{% extends "base.html" %}
{% block content %}
<!-- {{object}} -->
<div class="table table-responsive">
    <div class="card">
        <div class="card-body">
            <table class="table">
                <tr>
                    <td>Matakuliah</td>
                    <td>{{object.mk}}</td>
                    <td>Kelas</td>
                    <td>{{object.kelas}}</td>
                    <td>Tahun Ajaran</td>
                    <td>{{object.tahunAjaran}}</td>
                    
                </tr>
                <tr>
                    <td>Dosen</td>
                    <td>{{object.dosenPengajar}}</td>
                    <td>Semester</td>
                    <td>{{object.semester}}</td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>

    </div>
</div>
<div class="table table-responsive">
    <div class="card">
        <div class="card-header">
            Daftar Peserta Kuliah
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <td>#</td>
                    <th>NPM</th>
                    <th>Nama</th>
                </thead>
                <tbody>
                    
                    {% for pesertaKuliah in pstKuliah %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{pesertaKuliah.peserta__npm}}</td>
                            <td>{{pesertaKuliah.peserta__nama}}</td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3">Belum ada..!</td>
                        </tr>
                        
                    {% endfor %}
                        
                    <!-- GINI JUGA BISA  -->
                    <!-- {% if pstKuliah %}

                        <tr>
                            <td>npm</td>
                            <td>nama</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="2">Belum ada..!</td>
                        </tr>
                    {% endif %} -->
                    
                </tbody>
            </table>
            <a class="btn btn-primary btn-block" href="{% url 'olahDataJurnalKuliah:importPesertaKuliah' object.pk %}">Tambah Peserta Kuliah</a>
        </div>
    </div>
</div>
{% endblock content %}

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/jurnalKuliah_list.html
{% extends "base.html" %}
{% block content %}
<a class="btn btn-primary" href="{% url 'olahDataJurnalKuliah:jurnal-add' %}">Tambah Jurnal</a>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Matakuliah</th>
                <th>Tahun</th>
                <th>Smt</th>
                <th>Kls</th>
                <th>Dosen</th>
                <th>Edit / Hapus</th>
            </tr>
        </thead>
        <tbody>
            {% for jurnal in object_list %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>
                        <a href="{% url 'olahDataJurnalKuliah:detailjurnal' jurnal.pk %}">
                        {{jurnal.mk}}
                        </a>
                    </td>
                    
                    <td>{{jurnal.tahunAjaran}}</td>
                    <td>{{jurnal.semester}}</td>
                    <td>{{jurnal.kelas}}</td>
                    <td>{{jurnal.dosenPengajar}}</td>
                    <td>
                        <a class="btn btn-outline-success"
                            href="{% url 'olahDataJurnalKuliah:jurnal-update' jurnal.pk %}">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="btn btn-outline-danger" 
                            href="{% url 'olahDataJurnalKuliah:jurnal-delete' jurnal.pk %}">
                            <i class="fa fa-trash"></i>
                    </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">Belum ada jurnal</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/jurnalkuliah_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h2></h2>
<hr>
<div>
    <form action="" method="post">{% csrf_token %}
        <p>Yakin ingin menghapus jurnal perkuliahan "{{ object }}"?</p>
        <input type="submit" value="Confirm"/>
    </form>
</div>
{% endblock content %}

backend/simprosis/olahDataJurnalKuliah/templates/olahDataJurnalKuliah/jurnalkuliah_form.html
{% extends 'base.html' %}
{% block content %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

  <form method="post">
      {% csrf_token %}
      {{form}}
      <!-- {% for formReferensi in referensi_form %}
        {{formReferensi.label}}
        {{formReferensi}}
      {% endfor %} -->
      <br>
      <button class="btn btn-primary" type="submit">Simpan</button>
  </form>
{% endblock content %}